### ISSUE TITLE
Some delegate methods don't get called

### ISSUE THREAD

**Issue by maxydon** [sammcewan/WYPopoverController#37] opened 2014-11-19 19:03 UTC
popoverControllerDidPresentPopover gets called correctly but popoverControllerDidDismissPopover never gets called.

**Comment by vitalys** [comment] 2015-12-02 16:55
I believe your issue is a duplicate of #42, so I'm closing it. 
Feel free to reopen it if you have a different problem, but add more details. 
Thanks.

**Closed by vitalys** 2015-12-02 16:55 UTC
